"""add telegram_title and approved fields to Group model and add telegram_first_name, telegram_last_name and telegram_username fields to Player model

Revision ID: 104786831912
Revises: a0a6e3f6cf9f
Create Date: 2025-04-17 23:38:43.461896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '104786831912'
down_revision: Union[str, None] = 'a0a6e3f6cf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('telegram_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('group', sa.Column('approved', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_group_telegram_title'), 'group', ['telegram_title'], unique=False)
    op.add_column('player', sa.Column('telegram_first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('player', sa.Column('telegram_last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('player', sa.Column('telegram_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_player_telegram_first_name'), 'player', ['telegram_first_name'], unique=False)
    op.create_index(op.f('ix_player_telegram_username'), 'player', ['telegram_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_telegram_username'), table_name='player')
    op.drop_index(op.f('ix_player_telegram_first_name'), table_name='player')
    op.drop_column('player', 'telegram_username')
    op.drop_column('player', 'telegram_last_name')
    op.drop_column('player', 'telegram_first_name')
    op.drop_index(op.f('ix_group_telegram_title'), table_name='group')
    op.drop_column('group', 'approved')
    op.drop_column('group', 'telegram_title')
    # ### end Alembic commands ###
