"""add unique constraint to Player model

Revision ID: 2df1d50a648f
Revises: bd1a26d176fa
Create Date: 2025-04-09 12:40:37.010885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2df1d50a648f'
down_revision: Union[str, None] = 'bd1a26d176fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_group_telegram_id', 'player', ['group_id', 'telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_group_telegram_id', 'player', type_='unique')
    # ### end Alembic commands ###
