"""add approval_messages JSON field

Revision ID: 391a17f83d7d
Revises: 104786831912
Create Date: 2025-04-21 18:23:29.998877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '391a17f83d7d'
down_revision: Union[str, None] = '104786831912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('approval_messages', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'approval_messages')
    # ### end Alembic commands ###
