"""remove unique constraint on Player telegram_id

Revision ID: 78c9612a4af2
Revises: 391a17f83d7d
Create Date: 2025-04-23 23:57:58.180163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '78c9612a4af2'
down_revision: Union[str, None] = '391a17f83d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_telegram_id', table_name='player')
    op.create_index(op.f('ix_player_telegram_id'), 'player', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_telegram_id'), table_name='player')
    op.create_index('ix_player_telegram_id', 'player', ['telegram_id'], unique=True)
    # ### end Alembic commands ###
