"""add weight to Player model

Revision ID: 94fa23ba6cae
Revises: 2df1d50a648f
Create Date: 2025-04-09 18:13:37.276861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from config import DEFAULT_WEIGHT

# revision identifiers, used by Alembic.
revision: str = '94fa23ba6cae'
down_revision: Union[str, None] = '2df1d50a648f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('weight', sa.Integer(), nullable=False, server_default=str(DEFAULT_WEIGHT)))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'weight')
    # ### end Alembic commands ###
