"""add weight check constraint to Player model

Revision ID: 97e9062d5075
Revises: 94fa23ba6cae
Create Date: 2025-04-09 18:23:14.509508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from config import MAX_WEIGHT

# revision identifiers, used by Alembic.
revision: str = '97e9062d5075'
down_revision: Union[str, None] = '94fa23ba6cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        constraint_name="ck_weight_bounds",
        table_name="player",
        condition=f"weight >= 1 AND weight <= {MAX_WEIGHT}"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        constraint_name="ck_weight_bounds",
        table_name="player",
        type_="check"
    )
    # ### end Alembic commands ###
