"""add unique constraint and index on telegram_ids

Revision ID: a0a6e3f6cf9f
Revises: 97e9062d5075
Create Date: 2025-04-15 19:26:28.187189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0a6e3f6cf9f'
down_revision: Union[str, None] = '97e9062d5075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_group_telegram_id'), 'group', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_player_telegram_id'), 'player', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_telegram_id'), table_name='player')
    op.drop_index(op.f('ix_group_telegram_id'), table_name='group')
    # ### end Alembic commands ###
